# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Psychologue à Mons en Baroeul - Valérie Chappey
email: contact@psychologue.pro
description: > # this means to ignore newlines until "baseurl:"
 Que vous ayez besoin de conseils pour résoudre une difficulté ponctuelle ou d'un accompagnement psychothérapique approfondi, je mets mes compétences de Psychologue expérimentée au service de votre mieux-être.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://psychologue.pro" # the base hostname & protocol for your site

twitter:
  username: psychologue_pro
twitter_username: psychologue_pro

paginate: 12

paginate_path: "/blog/page-:num/"

permalink: "/blog/:title"

# Build settings
markdown: kramdown
gems:
   - jekyll-paginate
   - jekyll-mentions
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-redirect-from
   - jemoji
   - jekyll-seo-tag

facebook:
  app_id: 294710420547441
lang: fr_FR

social:
  name: Valérie Chappey
  links:
    - https://twitter.com/psychologue_pro
    - https://www.facebook.com/psychologue.pro
    - https://www.linkedin.com/in/psychologuepro/

author: Valérie Chappey
